version: '3.8'

services:
  web-mysql:
    image: mysql:8
    container_name: web-mysql
    ports:
      - "13306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=zz126578
      - MYSQL_DATABASE=lotto
  web:
    build:
      context: .
    container_name: web-server
    ports:
      - "80:8080"
    depends_on:
      - web-mysql